### ISSUE TITLE
Parsing multiple channel data

### ISSUE THREAD

**Issue by Junior-Wang** [tmkhoyan/cvyamlParser#2]
Thanks for you handy work. I made a small tweak in the `readcvYaml.cpp` file to parse multiple-channel data type in OpenCV (as shown in the attaching figure) which is not supported in the original project. Hope it useful.
![图片](https://user-images.githubusercontent.com/25879934/66395727-bfcd8300-ea0a-11e9-9f6e-291843f2d52b.png)
![图片](https://user-images.githubusercontent.com/25879934/66396104-98c38100-ea0b-11e9-9e79-ea406bc2eaa2.png)
![图片](https://user-images.githubusercontent.com/25879934/66396153-b4c72280-ea0b-11e9-8d62-17c17d8e419a.png)

**Comment by tmkhoyan** [comment]
Thanks! I will include it in the next update, along with possibility to read various maps and vector structures.

**Comment by tmkhoyan** [comment]
New release 2.0 added multichannel support and nested mixed structure support. See usage: https://youtu.be/jHjLLROfxhg

Release: https://github.com/tmkhoyan/cvyamlParser/releases/tag/v2.0
