### ISSUE TITLE
Error using recompiled

### ISSUE THREAD

**Issue by henryjliu** [tmkhoyan/cvyamlParser#5]
Am I correct that if I go to /mex I can call: 
b=readcvYaml('c:\test\test.yaml') and it should work since .mexw64 is precompiled for windows or do I always need to build it from source?

It says
Invalid MEX-file 'E:\github\cvyamlParser\mex\readcvYaml.mexw64': The specified module could not be found.
 
I assume it's missing some dll but the github file says dll was included in project.  Is there a link to the precompiled dll file?  I tried copying "opencv_core455.dll" but it still doesn't work - maybe file name issue?

**Comment by tmkhoyan** [comment]
Hi ,

Its always best to compile from source for your own system, but it should
still work as you describe. I tested it, as long as the mex file has access
to the opencv_world451.dll (or opencv_worldxx.dll) it should work. Try
putting the *_worldxx.dll, (NOT *_core.dll) in the working directory of
matlab.
You can also add it to you path variable via environment variables option
in windows, see screenshot. It must then point to the build/..../bin folder

Good luck.

Kind regards,
T

**Comment by tmkhoyan** [comment]
The required opencv_world451.dll file should be in the ./mex folder if you
download the project from github. If you have a windows installation of
open cv in my system it is ./OpenCV-xxx/opencv/build/x64/vc15/bin , built
with vs.

**Comment by henryjliu** [comment]
I cloned the repository and it wasn't there.   I had  opencv_world455.dll
and it didn't work but I renamed it  opencv_world451.dll and it's fine
now.  I did notice some small bug if the input file has a 0,0 matrix (I
saved a null matrix previously) it will fail completely.  Better if it just
kept going.  I deleted the null matrix from the file and the rest worked
fine.  Thanks for the addition!

Do you know if there is an update to OpenCV mex calls from matlab?

**Comment by tmkhoyan** [comment]
The .dll is not downloaded when you clone it via git due to gitignore. If
you just copy the folder its there.
A  [0.,0.,] matrix, so that is
 matA0_: !!opencv-matrix
   rows: 1
   cols: 2
   dt: d
   data: [ 0., 0. ]
works fine for me. Matrix [0] col-row=1, works as well.
 Did you check that the number of rows and columns are written correctly
to the yaml file? If you get an assertion error nelems ==
m.total()*m.channels(), then it has to do with the way its formatted.
Otherwise you can start an issue on github I ll check it when I have time.

Kind regards,
T

**Comment by henryjliu** [comment]
Thanks for clarification.  Perhaps update to readme it needs
opencv_world451.dll and it works fine would help others. You can try this
yaml file and it will error but again not a big deal as just don't save the
null ones a/b.

%YAML:1.0
---
a: !!opencv-matrix
   rows: 0
   cols: 0
   dt: u
   data: []
b: !!opencv-matrix
   rows: 0
   cols: 0
   dt: u
   data: []
k: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.1276953125000000e+02, 0., 6.4972528076171875e+02, 0.,
       9.1288311767578125e+02, 3.7234072875976562e+02, 0., 0., 1. ]

**Comment by tmkhoyan** [comment]
Yes, you are correct am empty matrix throws an error. I ll probably make a
fix for that and the readme some time, but not now. Thanks.

**Comment by tmkhoyan** [comment]
Issue solved. Closing. Readme will be updated
